### ISSUE TITLE
Organization and space 

### ISSUE THREAD

**Issue by benrouba** [watson-developer-cloud/sentiment-and-emotion#8]
i'm getting this error in the line command and i just don't understand  why 
No org and space targeted, use 'cf target -o ORG -s SPACE' to target an org and space
i put  my  name of the organization and my space  but i still have this error please help

**Comment by neil-boyette-ibm** [comment]
This is really a problem w/ signing into Bluemix and so the best place to get an answer would be at https://developer.ibm.com/answers/index.html

Note: it looks like you might be using an older version of the cli as the latest ones have moved over to a `bx ...` syntax.
